vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    artilleries:
      uri_prefix: /images/artillerie
      upload_destination: "%kernel.project_dir%/public/images/artillerie"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    # users:
    #   uri_prefix: /images/users
    #   upload_destination: "%kernel.project_dir%/public/images/users"
    #   namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #   inject_on_load: false
    #   delete_on_update: true
    #   delete_on_remove: true

  #mappings:
  #    products:
  #        uri_prefix: /images/products
  #        upload_destination: '%kernel.project_dir%/public/images/products'
  #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
